core/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('projects/', views.ProjectsView.as_view(), name='projects'),
    path('<slug:slug>/', views.ProjectDetailView.as_view(), name='project-detail'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    

core/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

class Project(models.Model):
    '''
    This model represents my projects
    '''
    title = models.CharField(max_length=150, null=True, blank=True)
    thumb_nail = models.ImageField(upload_to='uploads/static/img/projects', blank=True)
    description = models.TextField(max_length=2000, null=True, blank=True)
    challenges = models.TextField(max_length=2000, null=True, blank=True)
    deployed_url = models.CharField(max_length=150, null=True, blank=True)
    github_url = models.CharField(max_length=150, null=True, blank=True)
    technology = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(unique=True)
    python = models.BooleanField(default=False)
    django = models.BooleanField(default=False)
    javascript = models.BooleanField(default=False)
    jquery = models.BooleanField(default=False)
    react = models.BooleanField(default=False)
    html = models.BooleanField(default=False)
    css = models.BooleanField(default=False)
    postgresql = models.BooleanField(default=False)
    heroku = models.BooleanField(default=False)
    aws = models.BooleanField(default=False)

    class Meta:
        ordering = ['-title']

    def set_slug(self):
        '''Creates a unique slug for every project'''
        if self.slug:
            return
        slug = slugify(self.title)
        self.slug = slug
    
    def save(self, *args, **kwargs):
        '''Hides slug field in admin and saves slug to use in url'''
        self.set_slug()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("project-detail", args=[str(self.slug)])
    
    def __str__(self):
        return self.title

core/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    

core/views.py
from django.views.generic import TemplateView, ListView, DetailView
from core.models import Project 

class IndexView(ListView):
    model = Project
    queryset = Project.objects.order_by('-title')
    paginate_by = 3
    template_name = 'core/index.html'

class ProjectsView(ListView):
    model = Project
    queryset = Project.objects.order_by('-title')
    template_name = 'core/projects.html'

class AboutView(TemplateView):
    template_name = 'core/about.html'

class ProjectDetailView(DetailView):
    model = Project
    template = 'project_detail.html'
    slug_field = 'title'

core/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>Bailey Costin</title>
        <meta charset="utf-8">
        <meta name="description" content="">
        <link rel="shortcut icon" href="{% static '/img/orange_circle.png' %}" type="image/x-icon">
        <link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link href="https://fonts.googleapis.com/css?family=PT+Serif&display=swap" rel="stylesheet">        
        <link rel="stylesheet" href="{% static 'animate.css/animate.min.css' %}">
        <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
        <script src="{% static 'build/bundle.js' %}"></script>
        <script src="{% static 'rellax/rellax.min.js' %}"></script>
        <script src="{% static 'flowtype-js/index.js' %}"></script>
        <script src="{% static 'wow.js/dist/wow.min.js' %}"></script>
        <script>
              new WOW().init();
        </script>
    </head>
    <header>
        <div class="container hide-container">
            <div class="mobile-nav" role="navigation">
                <div id="menuToggle">
                    <input type="checkbox">
                    <span></span>
                    <span></span>
                    <span></span>
                    <ul id="menu">
                        <li class="list mt3">
                            <a class="link black" href="{% url 'index' %}">
                                Home
                            </a>
                        </li>
                        <li class="list">
                            <a class="link black" href="{% static "pdf/costinbresume.pdf" %}" target="_blank">
                                Resume   
                            </a>
                        </li>
                        <li class="list">
                            <a class="link black" href="{% url 'projects' %}">
                                Projects
                            </a>
                        </li>
                        <li class="list">
                            <a class="link black" href="mailto:bailey.costin@gmail.com">
                                Connect
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <nav class="top-nav">
            <ul class="flex list justify-end mt4 mr4 f4">
                <li><a class="nav-font ml1 link hover-orange dib pointer black" href="{% url 'index' %}">Home</a></li>
                <li class="nav-font ml1">-</li>
                <li><a class="nav-font ml1 link hover-orange dib pointer black" href="{% url 'projects' %}">Projects</a></li>
                <li class="nav-font ml1">-</li>
                <li><a class="nav-font ml1 link hover-orange dib pointer black" href="{% static "pdf/costinbresume.pdf" %}" target="_blank">Resume</a></li>
                <li class="nav-font ml1">-</li>
                <li><a class="nav-font ml1 link hover-orange dib pointer black" href="mailto:bailey.costin@gmail.com">Connect</a></li>
            </ul>
        </nav>
    </header>
    <body>
        <div class="sidenav title">
            <a href="{% url 'index' %}">
                <img class="logo title" src="{% static '/img/b_logo.png' %}" alt="Bailey's 'B' logo">
            </a>
            <div id="my_name" class="header-font title">
                Bailey Costin
            </div>
            <div class="sidenav-icons">
                <a class="sidenav-icons-spacing" href="{% url 'index' %}">
                    <i class="black pointer fas1 fas fa-home"></i>
                </a>
                <a class="sidenav-icons-spacing" href="{% static "pdf/costinbresume.pdf" %}" target="_blank">
                    <i id="sidenav-about-spacing" class="sidenav-left-spacing black pointer fas1 fas fa-user"></i>
                </a>
                <a class="sidenav-icons-spacing" href="{% url 'projects' %}">
                    <i class="black pointer fas1 fas fa-project-diagram"></i>
                </a>
                <a id="sidenav-contact-spacing" class="sidenav-icons-spacing" href="mailto:bailey.costin@gmail.com">
                    <i class="pointer black fas1 fas fa-envelope"></i>
                </a>
            </div>
        </div>
        <div class="main full-spacing">
            {% block content %}{% endblock %}
        </div>
    </body>
    <footer class="main full-spacing">
        <div class="footer">
            <img class="center-fit mt6 mr7" src="{% static '/img/bull_city_skyline.png' %}" alt="A silhouette drawing of the Durham skyline.">
            <div class="footer-bottom pa5">
                <div id="footer-header" class="mt4">
                    Let's be internet friends!
                </div>
                <div id="footer-body" class="mt3">
                    Feel free to reach out for collaborations or just a friendly hello! 😃
                </div>
                <div class="mt4">
                    <a href="https://www.linkedin.com/in/bailey-costin-7745b8179/" target="_blank"><img class="footer-icons pl3 pr3 pb3" src="{% static '/img/linkedin_white.png' %}" alt="The LinkedIn logo."></a>
                    <a href="https://github.com/bdcostin" target="_blank"><img class="footer-icons pl3 pr3 pb3"  src="{% static '/img/github_white.png' %}" alt="The GitHub logo."></a>
                </div>
                <div class="fine-print body-font gray">
                    <a class="gray link" href="https://github.com/bdcostin/portfolio" target="_blank">Source code</a> - © 2021
                </div>
            </div>
            <div>
                <div id="coordinates" class="white">
                    35.9940° N 78.8986° W
                </div>
            </div>
        </div>
    </footer>
</html>

core/templates/core/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div class="flex mt4">
    <img class="rellax mt4 about-img" data-rellax-speed="-2" src="{% static '/img/bw_me.jpg' %}" alt="">
    <div class="pl4 pr4 mt4 bio">
        Lorem ipsum dolor sit amet, ad saperet lucilius usu, pri no corpora epicurei efficiantur. No per solet apeirian elaboraret. Usu porro tritani interpretaris ne. Mei dolor omnium civibus te, qui ea officiis iracundia, te eam persius ponderum. An solum essent per, usu atqui vivendum tincidunt id, etiam putent cu cum.

        Sonet forensibus constituto has eu, ex mei gubergren comprehensam, qui ornatus assueverit reformidans ad. His omnium singulis pertinax ea, liber utroque vis ea. Nam an illum antiopam signiferumque, nec atqui latine oportere et, ex ius purto animal. Sea et saepe tractatos, ignota melius moderatius qui ne. Et graecis legendos adipisci pri, sea ei legere corrumpit. Sit putant deseruisse et.

        Ei amet suavitate vel, agam eligendi nam et. Est no populo appetere corrumpit. At scribentur dissentiunt mei. Nam te labore reprimique. Pri autem nonumy pericula cu.

        In qui nostro volumus fastidii. Diceret tacimates id his, choro explicari eu pri. Mei sumo euripidis in, te oratio decore incorrupte sit. Vel ut option denique minimum, ei velit inani consulatu nec. Mutat etiam conceptam pro ei, ut probatus delicatissimi mea. Vide commodo his ei, duo inermis fastidii lobortis at, pri et eirmod consetetur efficiantur.

        Nominavi ponderum ut eos, at timeam nominati usu. Ius ei wisi iuvaret quaeque, sit vide paulo ut, nibh altera pro ut. Modo utroque no sit, utinam voluptua deseruisse et his. Diam velit et nam, cu legere audire dolorem vix, ad vis utinam euismod.<br>
        <a class="projects-button mt4 f6 link dim ba bw2 ph3 pv2 mb2 dib" href="{% static "pdf/costinbresume.pdf" %}" target="_blank">Résumé</a>
    </div>
</div>

<script>
    var rellax = new Rellax('.rellax');
</script>
{% endblock %}

core/templates/core/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<h1 class="flex">
  <div class="rellax name" data-rellax-speed="-4">B</div>
  <div class="wow bounceInRight name"></div>
  <div class="wow bounceInRight rellax name" data-rellax-speed="-1" data-wow-delay=".2s">A</div>
  <div class="wow bounceInRight rellax name" data-rellax-speed="-7" data-wow-delay=".2s">I</div>
  <div class="wow bounceInRight rellax name" data-rellax-speed="-4" data-wow-delay=".2s">L</div>
  <div class="wow bounceInRight rellax name" data-rellax-speed="-3" data-wow-delay=".2s">E</div>
  <div class="wow bounceInRight rellax name" data-rellax-speed="-2" data-wow-delay=".2s">Y</div>
</h1>
<div class="flex">
    <div class="title-background">
        <div class="wow fadeInUp title mt6 ml4">is a Software Engineer</div>
    </div>
    <div class="plato ml5">
        <div class="rellax push-ab" data-rellax-speed="-4">
            <img class="wow fadeIn background-plato" src="{% static '/img/platologo2.png' %}" alt="An artist rendering of Plato, the Greek philosopher.">
        </div>
        <div class="rellax push-ab" data-rellax-speed="-3">
            <img class="wow fadeIn plato-speaks" data-wow-delay="1s" src="{% static '/img/plato_speaks.png' %}" alt="A speech bubble that says, this guy is a better developer than Socrates - Plato (probably)">
        </div>
    </div>
</div>
    <h2 class="header-font black f-5 mt5">
        Hey there! 👋🏼
    </h2>
<div class="flex">

    <div class="bio-box mt5">
        <div class="bio pa4">
            I am a Software Engineer II working on <a class="link lexis-link" href="https://www.lexisnexis.com/en-us/products/lexis-plus.page" target="_blank">Lexis+</a> at LexisNexis and currently live in the Raleigh-Durham area of North Carolina. Prior to working as a software engineer I attended <a class="link bootcamp-link" href="https://www.momentumlearn.com/" target="_blank">Momentum's coding bootcamp</a> in Durham, NC. The culmination of my bootcamp experience was leading a team that built Polimetrics, which is a Django web application that I conceptualized to poll presidential primary candidates using Tweet sentiment. I have previous work experience in the legal industry as a Senior Paralegal and hold a B.A. in Philosophy and Political Science with a minor in Philosophy, Politics, and Economics from the University of North Carolina at Chapel Hill.  
            <br>
            <br>
            I am customer obsessed, and I continuously strive to become a better developer, enhance the development community, and make the internet a more beautiful place. I am presently enhancing my knowledge of front-end frameworks and user-centric design. 
        </div>
    </div>
</div>
<h3 class="header-font black f-5 mt5 mb5">Some Side Projects</h3>
<div>
    <div class="project-background" data-rellax-zindex="6">
{% for project in project_list %}
    <div class="mt5 mr3 ml3 project-box">
        <a href="{% url 'project-detail' slug=project.title %}" style="background-image: url({{ project.thumb_nail.url }});"
        class="link mw5 dt hide-child br2 cover bg-center">
            <span class="body-font white dtc v-mid w-100 h-100 child bg-black-40 pa5 tc">
                {{project.description}}
            </span>
        </a>
        <div class="project-title tc mt4 mb3">{{ project }}</div>
        <div class="project-icons-index">
            <a class="link" href="{{ project.github_url }}" target="_blank">
                <i class="github-icons black fab fa-github" tooltip="Read Me" tooltip-position="bottom"></i>
            </a>
            {% if project.deployed_url %}
                <div>
                    <a class="link ml4" href="{{ project.deployed_url }}" target="_blank">
                        <i class="live-icon black fas fa-wifi" tooltip="Live Version" tooltip-position="bottom"></i>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}
    </div>
    <div class="project-background-bottom">
        <a class="projects-button f6 link dim ba bw2 ph3 pv2 dib" href="{% url 'projects' %}">View All</a>
    </div>
</div>
<div class="rellax push-ab" data-rellax-speed="-1">
    <img id="sun" src="{% static '/img/orange_circle.png' %}" alt="">
</div>
<script>
    var rellax = new Rellax('.rellax');
</script>
{% endblock %}

core/templates/core/project_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div class="header-font mt4 mb4 f-5">{{ project }}</div>
<div class="flex">
    <div class="project-thumbnail-box">
        <a href="{{ project.github_url }}" target="_blank">
            <img class="project-thumbnail mt4" src="{{ project.thumb_nail.url }}">
        </a>
    </div>
    <div class="project-description mr4 body-font body-line-height">
        {{ project.description }}
        {% comment %} {% if project.challenges != null %}
            <div class="header-font mt4 mb2 f-4">
                Challenges
            </div>
            <div>
                {{ project.challenges }}
            </div>
        {% endif %} {% endcomment %}
        <div class="project-icons-project-detail mt4">
            <a class="link" href="{{ project.github_url }}" target="_blank">
                <i class="github-icons black fab fa-github" tooltip="Read Me" tooltip-position="bottom"></i>
            </a>
            {% if project.deployed_url %}
                <div>
                    <a class="link ml4" href="{{ project.deployed_url }}" target="_blank">
                        <i class="live-icon black fas fa-wifi" tooltip="Live Version" tooltip-position="bottom"></i>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="header-font f-5 mt5 mb5">Stack</div>
<div class="tools-container">
    <div class="tools-small-container mt3 ml6 mr5 mb7">
        <ul class="list f-6 tool-box ml3 mr3">
        {% if project.python == True %}
            <li class="tools"><i class="devicon-python-plain colored"></i></li>
        {% endif %}
        {% if project.django == True %}
            <li class="tools"><i class="devicon-django-plain colored"></i></li>
        {% endif %}
        {% if project.javascript == True %}
            <li class="tools"><i class="devicon-javascript-plain colored"></i></li>
        {% endif %}
        {% if project.react == True %}
            <li class="tools"><i class="devicon-react-original colored"></i></li>
        {% endif %}
        {% if project.jquery == True %}
            <li class="tools"><i class="devicon-jquery-plain-wordmark colored"></i></li>
        {% endif %}  
        {% if project.html == True %}
            <li class="tools"><i class="devicon-html5-plain colored"></i></li>
        {% endif %} 
        {% if project.css == True %}
            <li class="tools"><i class="devicon-css3-plain colored"></i></li>
        {% endif %}    
        {% if project.postgresql == True %}
            <li class="tools"><i class="devicon-postgresql-plain colored"></i></li>
        {% endif %}     
        {% if project.heroku == True %}
            <li class="tools"><i class="devicon-heroku-plain colored"></i></li>
        {% endif %}     
        {% if project.aws == True %}
            <li class="tools"><i class="devicon-amazonwebservices-original colored"></i></li>
        {% endif %}      
        </ul>
    </div>
</div>
{% endblock %}

core/templates/core/projects.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<h1 id="projects-page-header" class="mt5 mb4">Work</h1>
<div class="projects-flex mt5 ml5">
{% for project in project_list %}
    <div class="mr4 mb6 ba bw2">
        <a href="{% url 'project-detail' slug=project.title %}">
            <img class="project-thumbnail mt4" src="{{ project.thumb_nail.url }}">
        </a>
        <div class="projects-header mb3 mt3 ml4">
            {{ project.title }}
        </div>
        <div class="ml4 project-icons">
            <a class="link" href="{{ project.github_url }}" target="_blank">
                <i class="github-icons black fab fa-github" tooltip="Read Me" tooltip-position="bottom"></i>
            </a>
            {% if project.deployed_url %}
                <div>
                    <a class="link ml4" href="{{ project.deployed_url }}" target="_blank">
                        <i class="live-icon black fas fa-wifi" tooltip="Live Version" tooltip-position="bottom"></i>
                    </a>
                </div>
            {% endif %}
        </div>
        <div class="ml4 mt3">
            <a class="projects-button pointer mb4 f6 link dim ba bw2 ph3 pv2 mb2 dib" href="{% url 'project-detail' slug=project.title %}">Details</a>
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}

core/templates/core/resume.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}


<a class="projects-button f6 link dim ba bw2 ph3 pv2 mb2 dib" href="{% static "pdf/bdcostinresume.pdf" %}" target="_blank">Download</a>
{% endblock %}